### PR TITLE
Update README.md broken link

### PR DESCRIPTION
**Pull request by cdsap**
issue #59  Updated Readme.md with the description of http://google.github.io/android-testing-support-library/docs/espresso/setup/index.html#setup-your-test-environment to disable animations

### CODE REVIEW

**Comment by cdsap** [comment]
I signed it!

**Comment by slinzner** [comment]
Thanks, totally forgot to change these after shutting down android-test-kit. Can you please sign the Google CLA, on top of the the Android CLA. Thanks.

**Comment by cdsap** [comment]
Done, I have signed Android CLA.

**Comment by JoseAlcerreca** [comment]
Thanks Iñaki!

The list you got it from has a formatting problem, can you change the format to this?

(On your device, under Settings->Developer options disable the following 3 settings: "Window animation scale", "Transition animation scale" and "Animator duration scale")

I'll fix the original list.

Thanks again!

**Comment by JoseAlcerreca** [comment]
Thanks again!

**Pull request merged**
