### PR TITLE
Fix all Bazel-enabled tests to pass with Bazel on HEAD again

### PR DESCRIPTION
**Pull request by jin**
Gradle tests:

```bash
$ for dir in BasicSample CustomMatcherSample DataAdapterSample IdlingResourceSample IntentsAdvancedSample IntentsBasicSample MultiWindowSample RecyclerViewSample
do 
  pushd ui/espresso/$dir
  ./gradlew connectedAndroidTest
  popd
done

...

$ echo $?
0
```

Bazel tests:

```
$ devbazel test //ui/espresso/... --incompatible_package_name_is_a_function=false 
INFO: Invocation ID: 33790409-cc14-4946-a162-754530b72389
INFO: Build option --cache_test_results has changed, discarding analysis cache.
INFO: Analysed 64 targets (0 packages loaded, 1967 targets configured).
INFO: Found 32 targets and 32 test targets...
INFO: Elapsed time: 0.585s, Critical Path: 0.02s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
//ui/espresso/BasicSample:BasicSampleInstrumentationTest_19_x86 (cached) PASSED in 72.2s
//ui/espresso/BasicSample:BasicSampleInstrumentationTest_21_x86 (cached) PASSED in 50.1s
//ui/espresso/BasicSample:BasicSampleInstrumentationTest_22_x86 (cached) PASSED in 74.5s
//ui/espresso/BasicSample:BasicSampleInstrumentationTest_23_x86 (cached) PASSED in 83.4s
//ui/espresso/CustomMatcherSample:CustomMatcherSampleInstrumentationTest_19_x86 (cached) PASSED in 95.2s
//ui/espresso/CustomMatcherSample:CustomMatcherSampleInstrumentationTest_21_x86 (cached) PASSED in 101.3s
//ui/espresso/CustomMatcherSample:CustomMatcherSampleInstrumentationTest_22_x86 (cached) PASSED in 109.1s
//ui/espresso/CustomMatcherSample:CustomMatcherSampleInstrumentationTest_23_x86 (cached) PASSED in 119.6s
//ui/espresso/DataAdapterSample:DataAdapterSampleInstrumentationTest_19_x86 (cached) PASSED in 84.8s
//ui/espresso/DataAdapterSample:DataAdapterSampleInstrumentationTest_21_x86 (cached) PASSED in 108.9s
//ui/espresso/DataAdapterSample:DataAdapterSampleInstrumentationTest_22_x86 (cached) PASSED in 96.9s
//ui/espresso/DataAdapterSample:DataAdapterSampleInstrumentationTest_23_x86 (cached) PASSED in 99.1s
//ui/espresso/IdlingResourceSample:IdlingResourceSampleInstrumentationTest_19_x86 (cached) PASSED in 70.2s
//ui/espresso/IdlingResourceSample:IdlingResourceSampleInstrumentationTest_21_x86 (cached) PASSED in 77.8s
//ui/espresso/IdlingResourceSample:IdlingResourceSampleInstrumentationTest_22_x86 (cached) PASSED in 67.8s
//ui/espresso/IdlingResourceSample:IdlingResourceSampleInstrumentationTest_23_x86 (cached) PASSED in 80.1s
//ui/espresso/IntentsAdvancedSample:IntentsAdvancedSampleInstrumentationTest_19_x86 (cached) PASSED in 62.7s
//ui/espresso/IntentsAdvancedSample:IntentsAdvancedSampleInstrumentationTest_21_x86 (cached) PASSED in 28.4s
//ui/espresso/IntentsAdvancedSample:IntentsAdvancedSampleInstrumentationTest_22_x86 (cached) PASSED in 60.2s
//ui/espresso/IntentsAdvancedSample:IntentsAdvancedSampleInstrumentationTest_23_x86 (cached) PASSED in 77.9s
//ui/espresso/IntentsBasicSample:IntentsBasicSampleInstrumentationTest_19_x86 (cached) PASSED in 31.7s
//ui/espresso/IntentsBasicSample:IntentsBasicSampleInstrumentationTest_21_x86 (cached) PASSED in 34.4s
//ui/espresso/IntentsBasicSample:IntentsBasicSampleInstrumentationTest_22_x86 (cached) PASSED in 34.5s
//ui/espresso/IntentsBasicSample:IntentsBasicSampleInstrumentationTest_23_x86 (cached) PASSED in 38.1s
//ui/espresso/MultiWindowSample:MultiWindowSampleInstrumentationTest_19_x86 (cached) PASSED in 77.9s
//ui/espresso/MultiWindowSample:MultiWindowSampleInstrumentationTest_21_x86 (cached) PASSED in 82.4s
//ui/espresso/MultiWindowSample:MultiWindowSampleInstrumentationTest_22_x86 (cached) PASSED in 89.6s
//ui/espresso/MultiWindowSample:MultiWindowSampleInstrumentationTest_23_x86 (cached) PASSED in 103.0s
//ui/espresso/RecyclerViewSample:RecyclerViewSampleInstrumentationTest_19_x86 (cached) PASSED in 68.4s
//ui/espresso/RecyclerViewSample:RecyclerViewSampleInstrumentationTest_21_x86 (cached) PASSED in 77.9s
//ui/espresso/RecyclerViewSample:RecyclerViewSampleInstrumentationTest_22_x86 (cached) PASSED in 77.9s
//ui/espresso/RecyclerViewSample:RecyclerViewSampleInstrumentationTest_23_x86 (cached) PASSED in 81.0s

Executed 0 out of 32 tests: 32 tests pass.
INFO: Build completed successfully, 1 total action
```

Fixes https://github.com/googlesamples/android-testing/issues/224

### CODE REVIEW

**Comment by jin** [comment]
Hmm.. odd, RecyclerViewSample is failing on CI but not locally.

```
11-30 12:38:04.265  2877  2877 E InstrumentationResultPrinter: Failed to mark test No Tests as finished after process crash
11-30 12:38:04.265  2877  2877 E MonitoringInstr: Exception encountered by: com.example.android.testing.espresso.RecyclerViewSample.MainActivity@1c8cb76. Dumping thread state to outputs and pining for the fjords.
11-30 12:38:04.265  2877  2877 E MonitoringInstr: android.content.res.Resources$NotFoundException: Resource ID #0x7f03001c
11-30 12:38:04.265  2877  2877 E MonitoringInstr: 	at android.content.res.Resources.getValue(Resources.java:1351)
11-30 12:38:04.265  2877  2877 E MonitoringInstr: 	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2774)
11-30 12:38:04.265  2877  2877 E MonitoringInstr: 	at android.content.res.Resources.getLayout(Resources.java:1165)
11-30 12:38:04.265  2877  2877 E MonitoringInstr: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:421)
11-30 12:38:04.265  2877  2877 E MonitoringInstr: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
11-30 12:38:04.265  2877  2877 E MonitoringInstr: 	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393)
11-30 12:38:04.265  2877  2877 E MonitoringInstr: 	at android.app.Activity.setContentView(Activity.java:2166)
11-30 12:38:04.265  2877  2877 E MonitoringInstr: 	at com.example.android.testing.espresso.RecyclerViewSample.MainActivity.onCreate(MainActivity.java:37)
11-30 12:38:04.265  2877  2877 E MonitoringInstr: 	at android.app.Activity.performCreate(Activity.java:6237)
11-30 12:38:04.265  2877  2877 E MonitoringInstr: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
11-30 12:38:04.265  2877  2877 E MonitoringInstr: 	at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:674)
11-30 12:38:04.265  2877  2877 E MonitoringInstr: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
11-30 12:38:04.265  2877  2877 E MonitoringInstr: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
11-30 12:38:04.265  2877  2877 E MonitoringInstr: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
11-30 12:38:04.265  2877  2877 E MonitoringInstr: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
11-30 12:38:04.265  2877  2877 E MonitoringInstr: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-30 12:38:04.265  2877  2877 E MonitoringInstr: 	at android.os.Looper.loop(Looper.java:148)
11-30 12:38:04.265  2877  2877 E MonitoringInstr: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
11-30 12:38:04.265  2877  2877 E MonitoringInstr: 	at java.lang.reflect.Method.invoke(Native Method)
11-30 12:38:04.265  2877  2877 E MonitoringInstr: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-30 12:38:04.265  2877  2877 E MonitoringInstr: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by jin** [comment]
Ok, I reproduced the failure with Bazel 0.19.2, the version on the CI. 

This CI breakage is **expected**, because before https://github.com/bazelbuild/bazel/commit/e2649cf4ee2d08ec803478650c20f8caa87ec440, Bazel erroneously used the **non-filtered** deploy jar in the test APK. The RecyclerViewSample test breakage is actually from the test APK being misled to look up the wrong resource ID. The commit is in 0.20.0 and later, which will make RecyclerViewSample pass.

**Comment by jin** [comment]
cc @meteorcloudy

**Comment by meteorcloudy** [comment]
IIUC, submitting this change will break Android Testing with Bazel 0.19? I suggest maybe we wait for 0.20.0 to be released?

**Comment by jin** [comment]
ping @brettchabot @slinzner

**Pull request merged**
